server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://ldqc.xyz/policelearning
#    username: root
#    password: mysqlpwd
    url: jdbc:mysql://10.135.8.168/policelearning
    username: root
    password: xlwc813913!
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

mybatis:
  mapper-locations: classpath:com/mapper/*.xml
  type-aliases-package: com.lyun.policelearning.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

config:
  jwt:
    secret: policelearning
    expire: 7200
    header: token

