server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ldqc.xyz:3306/policelearning
    username: policelearing
    password: f28oa11JYLYuFF56

mybatis:
  mapper-locations: classpath:com/mapper/*.xml
  type-aliases-package: com.lyun.policelearning.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql